version: '3.8'

# GPU overlay: Adds NVIDIA GPU support for local development
services:
  ollama:
    runtime: nvidia
    environment:
      - OLLAMA_KEEP_ALIVE=1h
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ollama_data:/root/.ollama
      # Mount WSL2 NVIDIA drivers for local development
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
