name: Quick Smoke Tests

on:
    workflow_dispatch:
    # Run after successful deployment
    workflow_run:
        workflows: ["ODRAS Comprehensive CI"]
        types:
            - completed

jobs:
    smoke-test:
        name: Quick Validation Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install minimal dependencies
              run: |
                  pip install requests pytest psycopg2-binary qdrant-client

            - name: Run quick validation script
              run: |
                  python -c "
                  import sys
                  sys.path.insert(0, '.')
                  from tests.test_comprehensive_suite import run_quick_validation
                  run_quick_validation()
                  "

            - name: Test critical endpoints
              run: |
                  # This would test against a deployed instance
                  # For now, we'll just validate the test files exist
                  test -f tests/test_comprehensive_suite.py
                  test -f tests/api/test_auth_endpoints.py
                  test -f tests/database/test_database_schema.py

                  echo "✓ All critical test files present"

            - name: Validate project structure
              run: |
                  # Check critical files and directories
                  CRITICAL_PATHS=(
                    "odras.sh"
                    "requirements.txt"
                    "backend/main.py"
                    "backend/migrations/migration_order.txt"
                    "tests/test_comprehensive_suite.py"
                    ".github/workflows/ci.yml"
                  )

                  for path in "${CRITICAL_PATHS[@]}"; do
                    if [ -e "$path" ]; then
                      echo "✓ Found: $path"
                    else
                      echo "✗ Missing: $path"
                      exit 1
                    fi
                  done

                  echo ""
                  echo "✓ All critical project files verified"
